on: [push, pull_request]

name: CI

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  check:
    name: Build, lint, test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          components: rustfmt, clippy

      - name: cargo build
        uses: actions-rs/cargo@v1
        with:
          command: build

      - name: cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all-features

      - name: cargo fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

      - name: cargo clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
  check-ui:
    name: Build, lint, test UI
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: caei-ui
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - run: npm ci

      - name: Lint
        run: npm run lint

      - name: Build
        run: npm run build

